spring:
  application:
    name: eureka-server

server:
  port: 8070

eureka:
  instance:
    hostname: ${HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: >
        http://eurekaserver1:8070/eureka/,
        http://eurekaserver2:8070/eureka/,
        http://eurekaserver3:8070/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"

